export default {
	hdr_simple: 0,
	hdr_level: 1,
	include: 1,
	mhdr_home_label: "LibCal",
	mhdr_home_url: "https://libcal.uky.edu",
	link1_label: "Stuff 1",
	link1_url: "https://google.com",
	link2_label: "Stuff 2",
	link2_url: "https://google.com",
	link3_label: "Stuff 3",
	link3_url: "https://google.com",
	link4_label: "Stuff 4",
	link4_url: "https://google.com",
	link5_label: "Stuff 5",
	link5_url: "https://google.com",
	link6_label: "Research Guides",
	link6_url: "https://libguides.uky.edu",
	hdr_srch_include: 1,
	hdr_width: 80,
	hdr_alert_include: 1,
	hdr_alert_title: "Unexpected Service Disruption",
	hdr_alert_msg:
		"We are currently working to resolve an authentication issue affect EBSCO databases.",
	hdr_alert_url_label: "More information",
	hdr_alert_url: "https://google.com",
};
