export default {
	hdr_simple: 1,
	include: 1,
	mhdr_home_label: "LibCal",
	mhdr_home_url: "https://libcal.uky.edu",
	"link1.label": "",
	"link1.url": "https://",
	"link2.label": "",
	"link2.url": "https://",
	"link3.label": "",
	"link3.url": "https://",
	"link4.label": "",
	"link4.url": "https://",
	"link5.label": "",
	"link5.url": "https://",
	"link6.label": "Research Guides",
	"link6.url": "https://libguides.uky.edu",
	hdr_srch_include: 0,
	hdr_width: 80,
	hdr_alert_include: 0,
	hdr_alert_title: "Unexpected Service Disruption",
	hdr_alert_msg:
		"We are currently working to resolve an authentication issue affect EBSCO databases.",
	hdr_alert_url_label: "More information",
	hdr_alert_url: "https://google.com",
};
