name: lint

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm

      - name: Install eslint
        run: npm install -g eslint

      - name: Run eslint
        run: eslint ./
