name: Lint

on:
  push:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install ESLint
        run: npm install @eslint/js --save-dev

      - name: Install globals
        run: npm install globals

      - name: Run ESLint with recommended rules
        run: npx eslint .
